### ISSUE TITLE
Playbook fails to execute in Exercise 2

### ISSUE THREAD

**Issue by maxiestudies** [nre-learning/nrelabs-curriculum#332]
**What Type of Issue Is This?**:

< Bug Report >

**Should this be assigned to you?**:

< No >

**Additional information**:

< In [Exercise 2](https://go.nrelabs.io/labs/?lessonSlug=ansible-network-automation&lessonStage=1) the playbook fails to execute. 
Here is the output from the console:
```yaml
fatal: [vqfx1]: FAILED! => changed=false 
  ansible_facts: {}
  failed_modules:
    junos_facts:
      ansible_facts:
        discovered_interpreter_python: /usr/bin/python3.6
      failed: true
      invocation:
        module_args:
          config_format: text
          gather_network_resources: null
          gather_subset:
          - all
          host: null
          password: null
          port: null
          provider: null
          ssh_keyfile: null
          timeout: null
          transport: null
          username: null
      msg: 'Negotiation failed: Error reading SSH protocol banner'
  msg: |-
    The following modules failed to execute: junos_facts 
```
>
